# Generated by Django 4.2 on 2023-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Byuers'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
    ]
