# Generated by Django 4.2 on 2023-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_buyer_options_alter_seller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
    ]
