# Generated by Django 4.2 on 2023-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="photo",
            field=models.ImageField(blank=True, upload_to="seller_photos/"),
        ),
    ]
