# Generated by Django 4.2 on 2023-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_seller_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
