# Generated by Django 4.2 on 2023-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_seller_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="seller",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
