# Generated by Django 4.2 on 2023-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_seller_city_seller_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="house_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
