# Generated by Django 4.2 on 2023-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chatroom_created_at_remove_chatroom_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="unread_messages_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
