# Generated by Django 4.2 on 2023-05-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
