# Generated by Django 4.2 on 2023-05-07 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_product_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(blank=True, editable=False, related_name='products_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
